#
#  Version 17.06.0-ce-mac19 (18663)
# firren <firren@163.com>
#
FROM mysql:5.6









#创建镜像
#docker build -t mysql:5.6 .

#创建容器
#公司容器位置
#docker run -p 3307:3306 --name mymysql -v ~/www/mydocker/mysql/logs:/var/log/mysql -v ~/www/mydocker/mysql/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 -d mysql:5.6
#个人容器位置
#docker run -p 3306:3306 --name mysql -v ~/docker/mysql/logs:/var/log/mysql -v ~/docker/mysql/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 -d mysql:5.6



